modLoader="javafml" #mandatory
loaderVersion="[25,)" #botania has 28+

[[mods]]
modId="nostrumfairies"
version="${file.jarVersion}"
displayName="Nostrum Fairies"
#logoFile="examplemod.png" #optional
description='''
Fairy-based logistics add-on for Nostrum Magica
'''

[[dependencies.nostrumfairies]]
	modId="forge"
	mandatory=true
	versionRange="[28.1.92,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.nostrumfairies]]
	modId="nostrummagica"
	mandatory=true
	versionRange="[1.14.4-1.10.0,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.nostrumfairies]]
	modId="nostrumaetheria"
	mandatory=true
	versionRange="[1.14.4-1.2.0,)"
	ordering="AFTER"
	side="BOTH"