modLoader="javafml" #mandatory
loaderVersion="[36,)"

# The license for your mod. This is mandatory and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All Rights Reserved"

[[mods]]
modId="nostrumfairies"
version="${file.jarVersion}"
displayName="Nostrum Fairies"
#logoFile="examplemod.png" #optional
authors="Skyler Manzanares"
description='''
Fairy-based logistics add-on for Nostrum Magica
'''

[[dependencies.nostrumfairies]]
	modId="forge"
	mandatory=true
	versionRange="[36,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.nostrumfairies]]
	modId="nostrummagica"
	mandatory=true
	versionRange="[1.16.5-1.11.0,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.nostrumfairies]]
	modId="nostrumaetheria"
	mandatory=true
	versionRange="[1.16.5-1.3.0,)"
	ordering="AFTER"
	side="BOTH"